version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tutorpso_app
    ports:
      - "8000:80"
    environment:
      APP_NAME: TutorPSO
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000

      DB_CONNECTION: pgsql
      DB_HOST: aws-1-ap-northeast-1.pooler.supabase.com
      DB_PORT: 6543
      DB_DATABASE: postgres
      DB_USERNAME: postgres.spzxnzybmhjdqzlcuegp
      DB_PASSWORD: TutorPso26!


      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    volumes:
      - storage_data:/var/www/html/storage/app/public
    restart: unless-stopped

volumes:
  storage_data: